name: we_dont_pay_much
description: "We Don't Pay Much. Calculate Interest Rate"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.2.9+2

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  # i18n â€“ Flutter's built-in gen_l10n with intl
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2

  # State management (simple & flexible)
  provider: ^6.1.2

  # Persist theme + language
  shared_preferences: ^2.5.3

  # Scan installed apps (Android)
  device_apps: ^2.2.0

  # Optional: app/package info if you need it
  package_info_plus: ^8.0.0
  http: ^1.2.0

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Enables Flutter's gen_l10n for AppLocalizations
  generate: true

  # Where your icons/images live
  assets:
    - assets/icons/
    - assets/images/
